---
- name: Create folder
  file:
    path: /opt/apps/lmisite-test
    state: directory
  run_once: true  
    
- name: Create venv
  shell: "python3 -m virtualenv /opt/apps/lmisite-test/env"
  run_once: true

- name: Copy files
  synchronize:
    src: lmisite/
    dest: /opt/apps/lmisite-test/src
    delete: true
    rsync_opts:
    - "--exclude=/db.sqlite3"
    - "--exclude=/media"
    - "--exclude=/static"
  run_once: true

- name: Set media permissions
  file:
    path: /opt/apps/lmisite-test/src/media
    owner: www-data
    group: www-data
    recurse: true
  
- name: Copy db password
  template:
    src: templates/db_pass.j2
    dest: /opt/apps/lmisite-test/src/db_pass
    owner: www-data
    group: www-data
    mode: 0640
  run_once: true

- name: Copy db name
  template:
    src: templates/db_name.j2
    dest: /opt/apps/lmisite-test/src/db_name
    owner: www-data
    group: www-data
    mode: 0640
  run_once: true
  
- name: Create db
  mysql_db:
    name: lmisite-test
    encoding: utf8
    state: present
  
- name: Create db user
  mysql_user:
    name: lmisite-test
    host: "%"
    state: present
    password: "{{ db_pass_test }}"
    priv: "lmisite-test.*:ALL"
  run_once: true
  
- name: Install dependencies
  pip:
    requirements: /opt/apps/lmisite-test/src/requirements.txt
    state: latest
    virtualenv: /opt/apps/lmisite-test/env
  run_once: true

- name: Migrate database
  command: "/opt/apps/lmisite-test/env/bin/python3 /opt/apps/lmisite-test/src/manage.py migrate"
  
- name: Collect static 
  command: "/opt/apps/lmisite-test/env/bin/python3 /opt/apps/lmisite-test/src/manage.py collectstatic --noinput"

- name: Create uWSGI config
  file:
    path: /etc/uwsgi/vassals/lmisite-test.ini
    src: /etc/uwsgi/vassals/app.skel
    state: link
    
- name: Create nginx config
  copy:
    src: files/nginx
    dest: /etc/nginx/sites-enabled/lmisite-test

- name: Issue certificates
  shell: "certbot -m {{ letsencrypt_email }} --agree-tos --nginx -d louisemisellinteriors.co.uk -d www.louisemisellinteriors.co.uk -d test.louisemisellinteriors.co.uk -n certonly"
  args:
    creates: /etc/letsencrypt/live/louisemisellinteriors.co.uk

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
    
- name: Reload vassal
  command: "touch --no-dereference /etc/uwsgi/vassals/lmisite-test.ini"
  args:
    warn: false
